name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Crystal
      uses: crystal-lang/install-crystal@v1
      
    - name: Install dependencies
      run: shards install
      
    - name: Run tests
      run: crystal spec
      
    - name: Run ameba
      run: crystal lib/ameba/bin/ameba
