name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Crystal
      uses: crystal-lang/install-crystal@v1
      
    - name: Install dependencies
      run: shards install
      
    - name: Build release
      run: |
        mkdir -p dist
        crystal build --release src/nakiri.cr -o dist/nakiri
        strip dist/nakiri
        cd dist && tar czf nakiri-linux-x86_64.tar.gz nakiri
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/nakiri-linux-x86_64.tar.gz
        draft: false
        prerelease: false
